spring.application.name=godzillalocalfilmes

# Não incluir o stack trace nas respostas de erro
server.error.include-stacktrace=never

# Opcional: Não incluir detalhes da exceção
server.error.include-exception=false

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/godzillafilmes_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor (opcional)
server.port=8080

#JWT Secret Token Provider
jwt.secret=${SECRET_KEY}