spring.application.name=godzillalocalfilmes

# Configurações do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/godzillafilmes_db
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL no console (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor (opcional)
server.port=8080